Repository un-ts/eslint-plugin-import-x, pull requests merged in 2025-06, with the labels that each got.

#375 chore: remove unused hash util
  CHANGELOG.md
  package.json
  src/utils/hash.ts
  src/utils/index.ts
  test/utils/hash.spec.ts
  yarn.lock
Labels: internal

#382 chore: bump `unrs-resolver` to `v1.9.0`
  .changeset/silly-roses-repeat.md
  package.json
  test/fixtures/component.html
  yarn.lock
Labels: bug, dependencies

#386 feat: port `react-x/prefer-react-namespace-import` into `prefer-namespace-import`
  .changeset/light-llamas-return.md
  README.md
  docs/rules/prefer-namespace-import.md
  src/index.ts
  src/rules/prefer-default-export.ts
  src/rules/prefer-namespace-import.ts
  test/rules/prefer-namespace-import.spec.ts
  test/utils.ts
Labels: enhancement

#389 test: only run pnp case for `test-compiled`
  test/fixtures.spec.ts
Labels: internal, test

#393 fix(extensions): always calculate `fix` option
  .changeset/angry-lions-learn.md
  docs/rules/extensions.md
  src/rules/extensions.ts
  test/rules/extensions.spec.ts
Labels: bug
